### ISSUE TITLE
Early return response

### ISSUE THREAD

**Issue by beanmoss** [markheramis/EnventOS#4]
https://github.com/markheramis/EnventOS/blob/b39648fb78e595ccc7769e5e866f3906c27585bb/app/Http/Controllers/OrdersController.php#L151

If you are not going to run the queries if there are no user_id/customer_id, you can return the response immediately without going further. 
If it is intended, please mark this as non issue/resolved.

**Comment by markheramis** [comment]
Hello,

Thank you for your feedback.

Do you mean that after

https://github.com/markheramis/EnventOS/blob/test/validation/app/Http/Controllers/OrdersController.php#L158

I put

``
if(!$user_id && !$customer_id){
response()->error('no user or customer provided');
}
``

Something like that?

**Comment by beanmoss** [comment]
Correct!

**Comment by markheramis** [comment]
Thank you so much for the feedback/tips/help.

https://github.com/markheramis/EnventOS/blob/dev/validation/app/Http/Controllers/OrdersController.php#L158

**Comment by beanmoss** [comment]
Should that be an `or` instead of `and`? Sorry im on mobile. Didnt see the prev snippets.
